- name: install and start apache
    hosts= webserver
    remote_user= vagrant
    become= yes

  tasks 
    -name install epel repo
     apt= name=epel-release state=present 

    -name install python bindings for SELinux
     apt= name={{item}} state=present
     with_items=
      - libselinux-python
      - libsemanage-python

    -name test to see if SELinux is running
     command= getenforce
     register= sestatus
     changed_when= false 

    -name install apache
     apt= name=httpd state=present

    -name start apache
     service: name=httpd state=started enable=yes 